import type { M5SKnowledgeEntry } from "./types";

const sourceIds = ["statuto-2025"];

export const M5S_PRINCIPLES: M5SKnowledgeEntry[] = [
  {
    id: "beni-comuni",
    type: "principle",
    title: "Beni comuni",
    summary: "I beni essenziali alla persona e alla comunità devono essere tutelati con gestione inclusiva e attenzione alle generazioni future; anche la conoscenza è considerata un bene comune.",
    keywords: ["beni comuni", "acqua", "aria", "foreste", "biodiversità", "patrimonio culturale", "conoscenza", "rete", "internet"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "ecologia-integrale",
    type: "principle",
    title: "Ecologia integrale",
    summary: "Lo sviluppo deve garantire benessere equo e sostenibile, proteggere ecosistemi e biodiversità e non compromettere i bisogni delle generazioni future.",
    keywords: ["ambiente", "ecologia", "clima", "transizione ecologica", "biodiversità", "inquinamento", "ecosistemi", "sostenibile"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "giustizia-sociale",
    type: "principle",
    title: "Giustizia sociale",
    summary: "La politica deve ridurre diseguaglianze economiche, sociali, di genere, generazionali e territoriali e rimuovere gli ostacoli alla piena partecipazione.",
    keywords: ["giustizia sociale", "diseguaglianza", "disuguaglianza", "povertà", "giovani", "donne", "genere", "coesione territoriale", "disabilità", "anziani"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "innovazione-tecnologica",
    type: "principle",
    title: "Innovazione tecnologica a misura di persona",
    summary: "Scienza e tecnologia devono migliorare la vita, ridurre le diseguaglianze e svilupparsi con controllo democratico, trasparenza e attenzione ai rischi di concentrazione del potere.",
    keywords: ["innovazione", "tecnologia", "intelligenza artificiale", "ia", "digitale", "ricerca", "scienza", "algoritmi"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "economia-eco-sociale",
    type: "principle",
    title: "Economia eco-sociale di mercato",
    summary: "Il mercato richiede una funzione regolatrice pubblica capace di contrastare concentrazioni di potere economico, tutelare ambiente e concorrenza e orientare produzione e consumi alla sostenibilità.",
    keywords: ["economia", "mercato", "imprese", "concorrenza", "monopoli", "consumatori", "produzione", "capitalismo", "regolazione"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "dignita-persona",
    type: "principle",
    title: "Dignità e rispetto della persona",
    summary: "La persona, nella sua concretezza e unicità, è al centro dell'azione politica; diritti, libertà fondamentali e autodeterminazione devono essere tutelati senza discriminazioni.",
    keywords: ["persona", "dignità", "diritti", "libertà", "discriminazione", "identità di genere", "orientamento sessuale", "laicità"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "pace-multilateralismo",
    type: "principle",
    title: "Pace e multilateralismo",
    summary: "La pace è un principio fondamentale; l'azione internazionale privilegia multilateralismo, dialogo, cooperazione e stabilizzazione del Mediterraneo nel quadro dell'appartenenza europea.",
    keywords: ["pace", "guerra", "ucraina", "palestina", "israele", "nato", "difesa", "armi", "multilateralismo", "mediterraneo", "politica estera"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "democrazia-partecipativa",
    type: "principle",
    title: "Democrazia rappresentativa e partecipativa",
    summary: "Il rapporto tra cittadini e rappresentanti deve essere continuo e la democrazia rappresentativa va affiancata da strumenti che coinvolgano direttamente i cittadini nelle decisioni collettive.",
    keywords: ["democrazia", "partecipazione", "referendum", "voto", "cittadini", "consultazione", "iniziativa popolare", "assemblea"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "politica-servizio",
    type: "principle",
    title: "Politica come servizio",
    summary: "La politica deve perseguire l'interesse complessivo della comunità e migliorare le condizioni di vita, evitando vantaggi particolari per singoli gruppi o persone.",
    keywords: ["politica", "servizio", "interesse pubblico", "comunità", "privilegi", "casta", "istituzioni"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "etica-pubblica",
    type: "principle",
    title: "Etica pubblica e responsabilità politica",
    summary: "Chi esercita funzioni pubbliche deve agire con disciplina, onore, correttezza e responsabilità politica, che non coincide soltanto con la responsabilità penale.",
    keywords: ["etica pubblica", "responsabilità politica", "disciplina", "onore", "correttezza", "incarichi pubblici"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "legalita-anticorruzione",
    type: "principle",
    title: "Legalità e contrasto a corruzione e criminalità",
    summary: "Legalità, contrasto alle organizzazioni criminali e alla corruzione sono condizioni per tutelare cittadini, imprese oneste e risorse collettive.",
    keywords: ["legalità", "corruzione", "mafia", "antimafia", "criminalità", "evasione", "appalti", "whistleblower"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "trasparenza-semplificazione",
    type: "principle",
    title: "Trasparenza e semplificazione",
    summary: "Le istituzioni devono rendere conto del proprio operato e la pubblica amministrazione deve offrire procedimenti chiari, semplici e paritari a cittadini e imprese.",
    keywords: ["trasparenza", "semplificazione", "pubblica amministrazione", "burocrazia", "rendicontazione", "accesso agli atti"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "cittadinanza-attiva",
    type: "principle",
    title: "Cittadinanza attiva",
    summary: "La politica vive anche fuori dalle istituzioni: attivismo civico, associazionismo e iniziative dei cittadini devono essere sostenuti per rendere effettivi i diritti e promuoverne di nuovi.",
    keywords: ["cittadinanza attiva", "attivismo", "territorio", "residenti", "quartiere", "municipio", "segnalazioni", "associazioni"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "diritto-salute",
    type: "principle",
    title: "Diritto alla salute",
    summary: "La salute comprende benessere fisico, psicologico e sociale; il Servizio sanitario nazionale e una sanità pubblica di qualità devono garantire accesso universale.",
    keywords: ["sanità", "salute", "ssn", "ospedale", "medici", "liste d'attesa", "prevenzione", "cure"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "istruzione-cultura",
    type: "principle",
    title: "Diritto all'istruzione e alla cultura",
    summary: "Istruzione, formazione e cultura pubbliche di qualità devono essere accessibili, inclusive e capaci di favorire consapevolezza, dialogo e partecipazione democratica.",
    keywords: ["scuola", "istruzione", "università", "ricerca", "cultura", "formazione", "studenti", "docenti"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "diritto-lavoro",
    type: "principle",
    title: "Diritto al lavoro dignitoso",
    summary: "Il lavoro deve garantire retribuzione giusta, sicurezza, qualità dell'occupazione, crescita personale e compatibilità con il tempo di vita.",
    keywords: ["lavoro", "salario", "stipendio", "precariato", "sicurezza sul lavoro", "orario", "smart working", "disconnessione"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "imprese-responsabili",
    type: "principle",
    title: "Imprese responsabili",
    summary: "L'impresa crea valore e occupazione ma deve considerare l'impatto delle proprie attività sull'ambiente, sui diritti e sul benessere dei lavoratori.",
    keywords: ["impresa", "imprese", "pmi", "azienda", "lavoratori", "responsabilità sociale", "produzione"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "sussidiarieta",
    type: "principle",
    title: "Sussidiarietà",
    summary: "I bisogni dei cittadini possono essere affrontati efficacemente dagli enti territoriali più vicini e dalle iniziative civiche e del terzo settore.",
    keywords: ["sussidiarietà", "comune", "municipio", "regione", "enti locali", "terzo settore", "territorio"],
    sourceIds,
    status: "foundational",
  },
  {
    id: "cura-parole",
    type: "principle",
    title: "Cura delle parole",
    summary: "Il linguaggio politico deve favorire coesione e confronto rispettoso: aggressività verbale, superficialità e dichiarazioni irriflesse sono incompatibili con un dibattito responsabile.",
    keywords: ["linguaggio", "parole", "insulti", "aggressività", "odio", "dibattito", "comunicazione"],
    sourceIds,
    status: "foundational",
  },
];
